# Generated by Django 4.2.6 on 2023-10-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedFileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_name', models.CharField(max_length=255)),
                ('encode_algorithm', models.CharField(max_length=255)),
                ('encoded_name', models.CharField(max_length=255)),
            ],
        ),
    ]
