# Generated by Django 4.2.6 on 2023-10-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encodeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encodedfilename',
            old_name='encode_algorithm',
            new_name='key',
        ),
    ]
