# Generated by Django 4.2.6 on 2023-10-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encodeapp', '0002_rename_encode_algorithm_encodedfilename_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncodedFileName',
        ),
    ]
