# Generated by Django 4.2.6 on 2023-10-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encodeapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncodedFileName',
        ),
    ]
