trigger:
- azpipeline

pool:
  vmImage: ubuntu-latest
## Set up variable from library
variables: 
  - group: demogroup
  ## Add this under variables section in the pipeline
  - name: azSubscription
    value: $[variables.AZSUBSCRIPTION]
  - name : az_group
    value: $[variables.GRPNAME]
  - name: az_location
    value: $[variables.REGION]

## Validate the terraform
stages:
  - stage: ValidateTerraform
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
        - task: PublishBuildArtifacts@1
          displayName: Publish the artifact for terraform manifest
          inputs:
            TargetPath: '$(System.DefaultWorkingDirectory)/terraform'
            ArtifactName: 'terraform-manifest'
            publishLocation: Container
        - task: TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            backendServiceArm: 'demo-svc'
            backendAzureRmResourceGroupName: 'demogrp'
            backendAzureRmStorageAccountName: 'tfstate22801'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'tf-pipeline'

        - task: TerraformTaskV4@4
          displayName: Terrafrom Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            commandOptions: '-var ssh_public_key=$(sshkey.secureFilePath)'