version: '3.0'
services:
  db:
    build: ./db
    restart: always
    env_file:
      - ./venv/webapp.env
    ports:
      - 5432:5432
  web:
    build: ./WebApp
    env_file:
      - ./venv/webapp.env
    ports:
      - 80:8000
    depends_on:
      - db    