apiVersion: v1
kind: Pod
metadata:
  name: django-demo
  namespace: webapp
  labels: 
    app: django-app
spec:
  containers:
    - name: webapp
      image: dnguyen332/djangowebapp:web
      command: ["python","patientencode/manage.py","runserver","0.0.0.0:8000"]
      envFrom:
        - configMapRef:
            name: envars-demo
      ports:
        - containerPort: 8000
        - containerPort: 5432
  initContainers:
  - name: check-db
    image: postgres:latest
    envFrom:
    - configMapRef:
        name: envars-demo
    command: ['sh', '-c', 'until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do echo waiting for database; sleep 2; done;']
