- name: Setup hosts config
  hosts: localhost 
  gather_facts: false 
  tasks:
    - name: Set variable for ansible playbook
      set_fact:
        terraform_outputs: "{{ lookup('file', 'config/tf-outputs.json') | from_json }}"
        ssh_key_file: "../.ssh/id_demovm"
        inventory_file: "config/hosts_inventory.yml"
    - name: Generate inventory content
      template:
        src: "../template/ansible-config/hosts_template.j2"
        dest: "{{ inventory_file }}"
    - name: Debug the host inventory file
      debug:
        msg: "{{ lookup('file', 'config/hosts_inventory.yml') | from_yaml }}"

- name: Prepare the AKS Manifest
  hosts: jumphost  # Replace 'jumphost' with the actual hostname or group for your jump host
  gather_facts: false
  tasks:
    - name: Copy AKS Manifest and Deployment Script
      ansible.builtin.copy:
        src: "../aks-define"
        dest: "~/demo"
      register: copy_result

    - name: Copy Deployment Script
      ansible.builtin.copy:
        src: "../scripts/deploypod.sh"
        dest: "~/demo/scripts/"
      register: script_copy_result

      
    - name: Copy Detroy Script
      ansible.builtin.copy:
        src: "../scripts/deletedeploy.sh"
        dest: "~/demo/scripts/"
      register: script_copy_result